export type PlannedRoute = {
  path: string;
  title: string;
  purpose: string;
  milestone: "M1" | "M2" | "M3" | "M4" | "M5";
  access: "public" | "demo" | "signed-in" | "shared-link";
};

export const plannedRoutes: readonly PlannedRoute[] = [
  {
    path: "/",
    title: "Subcontractor Margin Chain — protect job margin",
    purpose: "Landing page and live product preview",
    milestone: "M1",
    access: "public",
  },
  {
    path: "/demo",
    title: "Demo — Subcontractor Margin Chain",
    purpose: "Isolated sample job register",
    milestone: "M1",
    access: "demo",
  },
  {
    path: "/demo/chains/new",
    title: "New demo job — Subcontractor Margin Chain",
    purpose: "Create a job chain in the sandbox",
    milestone: "M1",
    access: "demo",
  },
  {
    path: "/demo/chains/:chainId",
    title: "Demo job — Subcontractor Margin Chain",
    purpose: "Review margin, scope, cost, approval, and invoices",
    milestone: "M1",
    access: "demo",
  },
  {
    path: "/privacy",
    title: "Privacy — Subcontractor Margin Chain",
    purpose: "Privacy terms in plain words",
    milestone: "M1",
    access: "public",
  },
  {
    path: "/terms",
    title: "Terms — Subcontractor Margin Chain",
    purpose: "Service and demo terms",
    milestone: "M1",
    access: "public",
  },
  {
    path: "/404",
    title: "Page not found — Subcontractor Margin Chain",
    purpose: "Designed recovery route",
    milestone: "M1",
    access: "public",
  },
  {
    path: "/auth/callback",
    title: "Signing in — Subcontractor Margin Chain",
    purpose: "Complete the Sociobot Entra redirect",
    milestone: "M2",
    access: "public",
  },
  {
    path: "/onboarding",
    title: "Set up your agency — Subcontractor Margin Chain",
    purpose: "Create the first organization and margin defaults",
    milestone: "M2",
    access: "signed-in",
  },
  {
    path: "/app/chains/new",
    title: "New job chain — Subcontractor Margin Chain",
    purpose: "Create a live tenant job chain",
    milestone: "M2",
    access: "signed-in",
  },
  {
    path: "/app/chains",
    title: "Job chains — Subcontractor Margin Chain",
    purpose: "Live tenant job register",
    milestone: "M2",
    access: "signed-in",
  },
  {
    path: "/app/chains/:chainId",
    title: "Job chain — Subcontractor Margin Chain",
    purpose: "Live job chain workspace",
    milestone: "M2",
    access: "signed-in",
  },
  {
    path: "/settings/team",
    title: "Team access — Subcontractor Margin Chain",
    purpose: "Memberships, invitations, and rate visibility",
    milestone: "M2",
    access: "signed-in",
  },
  {
    path: "/settings/billing",
    title: "Plan and billing — Subcontractor Margin Chain",
    purpose: "Subscription and active-chain allowance",
    milestone: "M2",
    access: "signed-in",
  },
  {
    path: "/app/chains/:chainId/history",
    title: "Commercial history — Subcontractor Margin Chain",
    purpose: "Review append-only scope and cost revisions",
    milestone: "M3",
    access: "signed-in",
  },
  {
    path: "/approve/:token",
    title: "Review scope — Subcontractor Margin Chain",
    purpose: "Expiring client approval link",
    milestone: "M3",
    access: "shared-link",
  },
  {
    path: "/submit/:token",
    title: "Submit an invoice — Subcontractor Margin Chain",
    purpose: "Restricted subcontractor invoice link",
    milestone: "M3",
    access: "shared-link",
  },
  {
    path: "/settings/access-links",
    title: "Shared access — Subcontractor Margin Chain",
    purpose: "Review and revoke external access links",
    milestone: "M3",
    access: "signed-in",
  },
  {
    path: "/app/notifications",
    title: "Notifications — Subcontractor Margin Chain",
    purpose: "Review commercial notices",
    milestone: "M4",
    access: "signed-in",
  },
  {
    path: "/app/activity",
    title: "Activity — Subcontractor Margin Chain",
    purpose: "Auditable organization activity",
    milestone: "M4",
    access: "signed-in",
  },
  {
    path: "/settings/notifications",
    title: "Notification settings — Subcontractor Margin Chain",
    purpose: "Choose in-app and email notices",
    milestone: "M4",
    access: "signed-in",
  },
  {
    path: "/settings/data",
    title: "Data and export — Subcontractor Margin Chain",
    purpose: "Export, retention, and organization deletion",
    milestone: "M4",
    access: "signed-in",
  },
  {
    path: "/ops",
    title: "Service operations — Subcontractor Margin Chain",
    purpose: "Redacted factory operations view",
    milestone: "M4",
    access: "signed-in",
  },
  {
    path: "/settings/import",
    title: "Import job chains — Subcontractor Margin Chain",
    purpose: "Spreadsheet migration with a dry run",
    milestone: "M5",
    access: "signed-in",
  },
  {
    path: "/settings/integrations",
    title: "Integrations — Subcontractor Margin Chain",
    purpose: "Manage signed webhooks and export shapes",
    milestone: "M5",
    access: "signed-in",
  },
  {
    path: "/settings/app",
    title: "Install the app — Subcontractor Margin Chain",
    purpose: "Installable app help and status",
    milestone: "M5",
    access: "signed-in",
  },
  {
    path: "/share/:token",
    title: "Shared job status — Subcontractor Margin Chain",
    purpose: "Revocable read-only commercial status",
    milestone: "M5",
    access: "shared-link",
  },
];
